### ISSUE TITLE
can't work on Android because the remote resource has time limit

### ISSUE THREAD

**Issue by MrZwqShuai** [react-native-community/react-native-video#1122]
### when I push the link just like 'http://m10.music.126.net/20180712154115/cdd7917d53f53529bea259a2054e5189/ymusic/aac8/e215/54a8/6c49025c90e6bd211bf61bd91efed99d.mp3' behind of  source={{ uri: 'this link'}}  , when I load the video/mp3,  my app get collapse quickly, it doesn't work any more, but when I download the mp3 source and put it on my own server, then I do the same work, it's work regularly， why ?  I think it must be the reason of this link ? can anyone help me , thanks  for a lot !

**Comment by cobarx** [comment]
Hi, I tried to access this link and there is no web server there anymore. If you are getting a time limit, something is wrong with the server - there's nothing we can do if the file goes away.
