### ISSUE TITLE
A problem occurred configuring project ':react-native-video'.       > Failed to find Platform SDK with path: platforms;android-27

### ISSUE THREAD

**Issue by TopGuo** [react-native-community/react-native-video#1202]
### Today I Use react-native on my project,
a poblem :A problem occurred configuring project ':react-native-video'.
      > Failed to find Platform SDK with path: platforms;android-27:
💯

**Comment by cobarx** [comment]
You need to install the Android 8.1 SDK or configure react-native-video to use the same SDK as your project as described at:
https://github.com/react-native-community/react-native-video#use-android-sdk-27-by-default
