### ISSUE TITLE
stereoPan not working react-native >=0.56

### ISSUE THREAD

**Issue by chankroesna** [react-native-community/react-native-video#1326]
### Work well
**stereoPan** work well when I am use with react-native 0.55.4 in separate index.android.js and index.ios.js

### Not working
**stereoPan** not working when I am try with react-native >= 0.56.0 and use only index.js .
I haven't try separate in react-native  >= 0.56.0.

Please help.

**Comment by cobarx** [comment]
@chankroesna Did you make sure you are using MediaPlayer for your 0.56 app? You have to override the default react-native-video link behavior to not use ExoPlayer.

**Comment by HeroSony** [comment]
@cobarx How to use MediaPlayer instead of ExoPlayer?
I am facing the same problem either.
