### ISSUE TITLE
iOS: RCTVideo setSrc: will block mainthread for long due to RCT setFilter:

### ISSUE THREAD

**Issue by niklassaers** [react-native-community/react-native-video#1348]
### Current behavior
When I instantiate a RCTVideo, setSrc is called. It in turn calls 
[self playerItemPrepareText:asset assetOptions:assetOptions withCallback:handler];
which calls
handler([AVPlayerItem playerItemWithAsset:asset]); (because I have no text tracks)
which in turn calls 
[self setFilter:_filterName];
setFilter takes between 0.3 and 2.8 seconds on my iPhone 7 Plus.

This all happens on the main thread, and thus I have a main thread block. In my case, since I'm loading multiple videos, I have a real bad hang.

### Reproduction steps
Load a video

### Expected behavior
Immediate return, anything that takes long will be done async

### Platform
iOS 12.1 
react-native-video/Video 4.0.1

**Comment by cobarx** [comment]
@nickgzzjr Can you take a look into this and see about making it so we don't create a filter unless the filter prop is set? I'd create a PR, but without doing some reading I'm not sure if it's even possible to change the composition on the fly.

Let me know if you can tackle this in the next few days as this is a pretty significant performance hit and it needs to get fixed as soon as we can.

**Comment by nickgzzjr** [comment]
@cobarx Not adding a filter at start is how I had originally done it but it didn't work for me. For some reason when you do apply the filter, the video transformation gets all messed up. On a side note: you can change the filter on the fly, as long as you start with a "blank" filter. I use this feature by swiping through different filters while the video is playing.

**Comment by niklassaers** [comment]
@nickgzzjr If also testing for an empty string, the PR works for me too. That's effectively what I've done in the meanwhile
