### ISSUE TITLE
Weird superfluous lines in the edges of video on iPhone 7/8 plus 

### ISSUE THREAD

**Issue by risingworld777** [react-native-community/react-native-video#1483]
### Current behavior
There are weird superfluous lines in the edges of video on iPhone 7/8 plus.
This issue happens only on iPhone 7/8 plus real devices.

### Platform
System:
      OS: macOS 10.14

Binaries:
      Node: 11.9.0 - /usr/local/bin/node
      npm: 6.5.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman

npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.0 => 0.56.0 

npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by juliafriberg** [comment]
@risingworld777 Did you solve it?

**Comment by risingworld777** [comment]
@juliafriberg  No I didn't solve it yet.
There is same issue https://github.com/react-native-community/react-native-video/issues/1638
