### ISSUE TITLE
Play Source code Data

### ISSUE THREAD

**Issue by xzudemimino** [react-native-community/react-native-video#2506]
Hello so i wanted to start a video from the folder where my source code is. 

/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 * @flow strict-local
 */

import React from 'react';
import Video from 'react-native-video';
import type {Node} from 'react';
import {
  SafeAreaView,
  ScrollView,
  StatusBar,
  StyleSheet,
  Text,
  useColorScheme,
  View,
} from 'react-native';
import {
  Colors,
  DebugInstructions,
  Header,
  LearnMoreLinks,
  ReloadInstructions,
} from 'react-native/Libraries/NewAppScreen';

const Section = ({children, title}): Node => {
  const isDarkMode = useColorScheme() === 'dark';
  return (
    <View style={styles.sectionContainer}>
      <Text
        style={[
          styles.sectionTitle,
          {
            color: isDarkMode ? Colors.white : Colors.black,
          },
        ]}>
        {title}
      </Text>
      <Text
        style={[
          styles.sectionDescription,
          {
            color: isDarkMode ? Colors.light : Colors.dark,
          },
        ]}>
        {children}
      </Text>
    </View>
  );
};

const App: () => Node = () => {
  const isDarkMode = useColorScheme() === 'dark';

  const backgroundStyle = {
    backgroundColor: isDarkMode ? Colors.darker : Colors.lighter,
  };
  const MyFile = require("./yt5s.com-test.mp4");
  return (
    <View>
      <Text>
        Test
      </Text>
      <Video
        source={MyFile}
      />
    </View>
  );
};

const styles = StyleSheet.create({
  sectionContainer: {
    marginTop: 32,
    paddingHorizontal: 24,
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: '600',
  },
  sectionDescription: {
    marginTop: 8,
    fontSize: 18,
    fontWeight: '400',
  },
  highlight: {
    fontWeight: '700',
  },
});

export default App;

the problem now is that via Android Studio he can´t load it it only display test.
In my cmd put out Error asset not found.

**Comment by kwarismian** [comment]
FYI, I had this same experience with Android Studio, but when testing a release build on a real device it worked perfectly.  Your results may vary, but I think this is more an issue with the emulation (and potentially debug mode) than the technique.

**Comment by xzudemimino** [comment]
I have tried to use my physical device and like in the android studio run i have problems with the asset.

**Comment by xzudemimino** [comment]
Now i have made an APK for Android the only issue is that he start the audio but didn´t show the Video, i have added to my code a style but it doesn´t worked,

**Comment by xzudemimino** [comment]
`/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 * @flow strict-local
 */
import { NavigationContainer } from '@react-navigation/native';
import React from 'react';
import Video from 'react-native-video';
import type { Node } from 'react';
import { createDrawerNavigator } from '@react-navigation/drawer';

import {
  SafeAreaView,
  ScrollView,
  StatusBar,
  StyleSheet,
  Text,
  useColorScheme,
  View,
} from 'react-native';
import {
  Colors,
  DebugInstructions,
  Header,
  LearnMoreLinks,
  ReloadInstructions,
} from 'react-native/Libraries/NewAppScreen';

const Section = ({children, title}): Node => {
  const isDarkMode = useColorScheme() === 'dark';
  return (
    <View style={styles.sectionContainer}>
      <Text
        style={[
          styles.sectionTitle,
          {
            color: isDarkMode ? Colors.white : Colors.black,
          },
        ]}>
        {title}
      </Text>
      <Text
        style={[
          styles.sectionDescription,
          {
            color: isDarkMode ? Colors.light : Colors.dark,
          },
        ]}>
        {children}
      </Text>
    </View>
  );
};
function LogIn({ navigation }) {
  
}
function HomeScreen({ navigation }) {

    const MyFile = require("./yt5s.com.mp4");
  
    return (
      <View style={styles.body}>
        <Text style={styles.ueberschrift}>
          Test
        </Text>
        <Video
          source={MyFile}
          audioOnly={false}
          style={styles.video}
          controls={true}
        />
      </View>
    );
}
class Test extends React.Component{
  render() {
    const { navigation } = this.props;
    const MyFile = require("./yt5s.com.mp4");
    return (
      <View style={styles.body}>
      <Text style={styles.ueberschrift}>
          Test
      </Text>
      <Video
          source={MyFile}
          audioOnly={false}
          style={styles.video}
          controls={true}
        />
      </View>
    )
  }
}
function Information({ navigation }) {
  return (
    <View>
      <Text>Hallo es freut mich das ihr auf dieser Seite gelandet seid.</Text>
      <Text>Diese App befindet sich noch in entwicklung und ich freue mich auf Feedback :)</Text>
    </View>
  )
}

const Drawer = createDrawerNavigator();



export default function App() {
  return (
    <NavigationContainer>
      <Drawer.Navigator initialRouteName="Home">
        <Drawer.Screen name="Test" component={Test}/>
        <Drawer.Screen name="Home" component={HomeScreen} />
        <Drawer.Screen name="Information" component={Information}/>
      </Drawer.Navigator>
    </NavigationContainer>
  )
}

const styles = StyleSheet.create({
  ueberschrift: {
    fontSize: 20,
  },
  body: {
margin: 10,
  },
  video: {
    position: 'absolute',
    weight: 300,
    height:300,
  },
  sectionContainer: {
    marginTop: 32,
    paddingHorizontal: 24,
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: '600',
  },
  sectionDescription: {
    marginTop: 8,
    fontSize: 18,
    fontWeight: '400',
  },
  highlight: {
    fontWeight: '700',
  },
});


`

So this is what i have now. You can see the control panel for a few seconds but after it disappers you don´t see anything of the video. You can hear the sound, but you can´t watch the clip.
