### ISSUE TITLE
In Android, ReactExoplayerView instance doesn't eliminate after JS component unmount.

### ISSUE THREAD

**Issue by YangJonghun** [react-native-community/react-native-video#3488]
# Bug

## Platform
* Android

## Environment info

Library version: 6.0.0-beta.4
Device: Android

## Steps To Reproduce
1. add below Log within `onHostPause` method
```
Log.d(TAG, "onHostPause: " + this.hashCode());
```
2. mount `<Video />` component
3. move to background
4. check log print properly (via Logcat)
```
ReactExoplayerView      <package name>      D  onHostPause: <instance hash code A>
```
5. move to foreground
6. unmount `<Video />` component you created in step 2
7. mount new `<Video />` component
8. move to background
9. you can check stacked log
```
ReactExoplayerView      <package name>      D  onHostPause: <instance hash code A>
ReactExoplayerView      <package name>      D  onHostPause: <instance hash code B>
```
10. repeat steps 5~9, you can see the logs overlap by the number of iterations.

## Expected behaviour
1. memory leak
2. calling unnecessary lifecycle callback

## FYI
This is not an issue in v5.2.1., something seems to have gone wrong with the update process so far

**Comment by YangJonghun** [comment]
PR #3380 missed unmount case
so I made PR #3489

**Comment by KrzysztofMoch** [comment]
Thanks for PR!, will be included in `6.0.0-beta.5`

**Comment by VMBindraban** [comment]
@KrzysztofMoch Do you have an ETA for the `6.0.0-beta.5` release?

**Comment by KrzysztofMoch** [comment]
Hey @VMBindraban, I am planing to make release this week (so max 5 days 😅)
