### ISSUE TITLE
[BUG]: Video is buffering and starting from 0 when I come back from another screen

### ISSUE THREAD

**Issue by kosmokoks** [react-native-community/react-native-video#3666]
### Version

v6 (Beta)

### What platforms are you having the problem on?

Android

### Architecture

Old architecture

### What happened?

Every time I return from another screen to the screen where the Video component is initialized, the video buffers and does not start from the moment I stopped watching, but starts from the beginning, this only happens on Android, on iOS, without any additional configurations, the video always remains in at the same moment and does not buffer again. Do you have any solution to save the video at a given second and not buffer it again?

### Reproduction

repository link

### Reproduction

Go to the view where the Video component is, 
go to a specific second in the video, 
go to another view,
go back to the video view and the video will start loading again

**Comment by freeboub** [comment]
you should check if the component is umounted.
If that is the case, this is the expected behavior.
you can either save playback position to be able to restore it (see startPosition prop)
either move the component out of this screen

**Comment by kosmokoks** [comment]
@freeboub thank you for replying

But on iOS the video does not buffer every time I enter the screen and the time remains unchanged. Is this caused by the cache, or does Android behave differently? Video on Android buffers every time and plays from the beginning when I move between the bottom tabs, and the video is on one of the tabs

**Comment by freeboub** [comment]
@kosmokoks is it possible to share a sample?

**Comment by kosmokoks** [comment]
We can close. It's a standard android behavior
