### ISSUE TITLE
[BUG]: isExternalPlaybackActive' is unavailable in visionOS

### ISSUE THREAD

**Issue by AdamGoodApp** [react-native-community/react-native-video#4079]
### Version

6.4.3

### What platforms are you having the problem on?

visionOS

### System Version

2.0

### On what device are you experiencing the issue?

Simulator

### Architecture

New architecture with interop layer

### What happened?

When building project I get the error `isExternalPlaybackActive' is unavailable in visionOS`

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are: 

Install react-native-video with npm
Run pod install
Build project in Xcode

**Comment by moskalakamil** [comment]
Hi, thanks for reporting the issue! isExternalPlaybackActive is not supported for visionOS rn, try to remove this prop for visionOS platform. @KrzysztofMoch should we convert this issue to feature request?

**Comment by freeboub** [comment]
@AdamGoodApp I just push a branch to fix the issue can you have a try on this branch please ?

**Comment by freeboub** [comment]
I finnally tested on apple vision pro on emulator, It works fine !

**Comment by AdamGoodApp** [comment]
RTCVideo.swift

```
func applicationWillResignActive(notification _: NSNotification!) {
        let isExternalPlaybackActive = _player?.isExternalPlaybackActive ?? false
        if _playInBackground || _playWhenInactive || !_isPlaying || isExternalPlaybackActive { return }

        _player?.pause()
        _player?.rate = 0.0
    }
```

`'isExternalPlaybackActive' is unavailable in visionOS`


"react-native-video": "^6.4.5" Upgraded npm package and ran pod install again.
